/*
 * ghostty_rs.h -- C ABI for the ghostty-rs engine (M5 FFI spike scope).
 *
 * GENERATED by cbindgen from crates/ghostty-ffi. DO NOT EDIT BY HAND.
 * Regenerate + drift-check: `cargo test -p ghostty-ffi header_drift`.
 *
 * Naming mirrors upstream include/ghostty.h (opaque handles, sized *_s
 * structs, *_e enums) so upstream's Swift sources can be ADAPTED, not
 * rewritten. See docs/analysis/ffi-spike.md for the threading contract and
 * the go/no-go note.
 */

#ifndef GHOSTTY_RS_H
#define GHOSTTY_RS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success sentinel, also exposed as a macro-style constant in the header for
 * callers that prefer `== GHOSTTY_RS_SUCCESS`.
 */
#define GHOSTTY_RS_SUCCESS (int32_t)GhosttyRsResult_Success

/**
 * See [`GhosttyRsResult::Panic`].
 */
#define GHOSTTY_RS_PANIC (int32_t)GhosttyRsResult_Panic

/**
 * Result code for the ghostty-rs C ABI. `0` is success; negatives are errors.
 *
 * Mirrors the `GhosttyResult` convention the differential harness already
 * binds (`crates/vt-diff/src/ffi.rs`), namespaced `_RS_` to avoid clashing
 * with a co-linked libghostty-vt.
 */
typedef enum {
  /**
   * The call succeeded.
   */
  GHOSTTY_RS_RESULT_SUCCESS = 0,
  /**
   * A required pointer argument was NULL.
   */
  GHOSTTY_RS_RESULT_NULL_ARGUMENT = -1,
  /**
   * An argument was out of range or otherwise invalid.
   */
  GHOSTTY_RS_RESULT_INVALID_VALUE = -2,
  /**
   * The caller-provided buffer was too small; `*out_len` holds the need.
   */
  GHOSTTY_RS_RESULT_OUT_OF_SPACE = -3,
  /**
   * A panic was caught at the FFI boundary (would have been UB to unwind).
   */
  GHOSTTY_RS_RESULT_PANIC = -100,
} GhosttyRsResult;

/**
 * Clipboard selection, mirroring upstream `ghostty_clipboard_e`.
 */
typedef enum {
  /**
   * The standard system clipboard (OSC 52 `c`).
   */
  GHOSTTY_RS_CLIPBOARD_STANDARD = 0,
  /**
   * The primary selection clipboard (OSC 52 `p`).
   */
  GHOSTTY_RS_CLIPBOARD_SELECTION = 1,
} GhosttyRsClipboard;

/**
 * Key action, mirroring upstream `ghostty_input_action_e`.
 */
typedef enum {
  /**
   * Key released.
   */
  GHOSTTY_RS_INPUT_ACTION_RELEASE = 0,
  /**
   * Key pressed.
   */
  GHOSTTY_RS_INPUT_ACTION_PRESS = 1,
  /**
   * Auto-repeat.
   */
  GHOSTTY_RS_INPUT_ACTION_REPEAT = 2,
} GhosttyRsInputAction;

/**
 * The app object. Owns the runtime config (callbacks + userdata) shared by its
 * surfaces. In the spike this is deliberately thin: upstream's app owns the
 * event loop; here it is the callback-holder + apartment root.
 *
 * Exported as opaque `ghostty_rs_app_t` (a pointer) in the header.
 */
typedef struct ghostty_rs_app_t ghostty_rs_app_t;

/**
 * The surface object: wraps a `Stream<TerminalHandler>` (the engine) plus a
 * back-pointer to its app so it can fire the app's clipboard/wakeup callbacks.
 *
 * Exported as opaque `ghostty_rs_surface_t` (a pointer) in the header.
 */
typedef struct ghostty_rs_surface_t ghostty_rs_surface_t;

/**
 * Wakeup callback: the engine asks the embedder to schedule a tick on its
 * event loop. **Callable from any thread** (see the threading contract). The
 * `void*` is the `userdata` from [`GhosttyRsRuntimeConfig`].
 */
typedef void (*GhosttyRsWakeupCb)(void *userdata);

/**
 * Write-clipboard callback: fired when the engine wants to set the clipboard
 * (OSC 52 write). `data` is the **raw, still-base64-encoded** OSC body (empty
 * string means "clear"), valid only for the duration of the call. Mirrors the
 * intent of upstream `ghostty_runtime_write_clipboard_cb` (simplified: no
 * mime/confirm plumbing in the spike). Main-thread-only.
 */
typedef void (*GhosttyRsWriteClipboardCb)(void *userdata, GhosttyRsClipboard kind, const char *data);

/**
 * Runtime configuration handed to [`ghostty_rs_app_new`]. Mirrors the shape of
 * upstream `ghostty_runtime_config_s` (subset: userdata + the two callbacks in
 * spike scope). Passed by const pointer; copied internally, so the caller's
 * struct need not outlive the call.
 */
typedef struct {
  /**
   * Opaque embedder pointer passed back to every callback.
   */
  void *userdata;
  /**
   * See [`GhosttyRsWakeupCb`]. May be NULL.
   */
  GhosttyRsWakeupCb wakeup_cb;
  /**
   * See [`GhosttyRsWriteClipboardCb`]. May be NULL.
   */
  GhosttyRsWriteClipboardCb write_clipboard_cb;
} GhosttyRsRuntimeConfig;

/**
 * Surface configuration handed to [`ghostty_rs_surface_new`]. Mirrors the role
 * of upstream `ghostty_surface_config_s` (spike subset: grid size + scrollback).
 */
typedef struct {
  /**
   * Width in cells; must be > 0.
   */
  uint16_t cols;
  /**
   * Height in cells; must be > 0.
   */
  uint16_t rows;
  /**
   * Maximum scrollback lines retained.
   */
  size_t max_scrollback;
} GhosttyRsSurfaceConfig;

/**
 * Modifier bitmask, mirroring upstream `ghostty_input_mods_e` (a packed set;
 * here a plain bitfield of the modifiers the spike encodes). LSB-first.
 */
typedef struct {
  /**
   * Packed bits: 1=shift, 2=ctrl, 4=alt, 8=super. Others reserved (0).
   */
  uint16_t bits;
} GhosttyRsInputMods;

/**
 * A key input event, mirroring upstream `ghostty_input_key_s`.
 *
 * `text` is an optional UTF-8, NUL-terminated string of the codepoint(s) this
 * key generated (may be NULL / empty for non-text keys). It is borrowed for
 * the duration of the call only.
 */
typedef struct {
  /**
   * Press / release / repeat.
   */
  GhosttyRsInputAction action;
  /**
   * Active modifiers.
   */
  GhosttyRsInputMods mods;
  /**
   * The text this key generated (UTF-8, NUL-terminated), or NULL.
   */
  const char *text;
  /**
   * The unshifted codepoint (0 = none). Used when `text` is NULL.
   */
  uint32_t unshifted_codepoint;
  /**
   * True while mid dead-key composition (event should not encode).
   */
  bool composing;
} GhosttyRsInputKey;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * One-time global initialization. Mirrors upstream `ghostty_init`. In the
 * spike there is no global state to set up (no logging/allocator wiring yet),
 * so this is a no-op that exists to lock the call ordering into the ABI.
 * Returns [`GHOSTTY_RS_SUCCESS`].
 */
GhosttyRsResult ghostty_rs_init(void);

/**
 * Create a new app from a runtime config. Returns NULL on a NULL `config` or a
 * caught panic. The returned handle must be freed with [`ghostty_rs_app_free`]
 * after all its surfaces are freed.
 */
ghostty_rs_app_t *ghostty_rs_app_new(const GhosttyRsRuntimeConfig *config);

/**
 * Advance the app one tick. In the spike the engine is synchronous, so this is
 * a no-op stand-in for upstream's event-loop pump; it exists so the Swift
 * driver's run loop can call it. NULL is a no-op.
 */
void ghostty_rs_app_tick(ghostty_rs_app_t *app);

/**
 * Free an app. Must be called after all its surfaces are freed. NULL is a
 * no-op.
 */
void ghostty_rs_app_free(ghostty_rs_app_t *app);

/**
 * Create a surface on `app` from a surface config. Returns NULL on a NULL
 * arg, an invalid (zero) grid size, or a caught panic.
 */
ghostty_rs_surface_t *ghostty_rs_surface_new(ghostty_rs_app_t *app,
                                             const GhosttyRsSurfaceConfig *config);

/**
 * Free a surface. NULL is a no-op.
 */
void ghostty_rs_surface_free(ghostty_rs_surface_t *surface);

/**
 * Feed raw PTY bytes (what a shell would print) into the surface's engine.
 * This is the path the eventual PTY reader thread's bytes take. After
 * processing, any OSC 52 clipboard write is fired via the app's callback, and
 * any engine reply bytes are queued internally (drain via
 * [`ghostty_rs_surface_take_pty_reply`], not required by the spike driver).
 *
 * Returns [`GhosttyRsResult::NullArgument`] on NULL, else `Success`.
 */
GhosttyRsResult ghostty_rs_surface_write_pty_bytes(ghostty_rs_surface_t *surface,
                                                   const uint8_t *data,
                                                   size_t len);

/**
 * Send a key event to the surface. The event is encoded to PTY bytes via
 * [`ghostty_input`] and fed straight back into the engine (mirroring how a
 * real surface routes key output to its PTY, then the PTY echoes it back). Any
 * resulting clipboard side effects are fired.
 *
 * Spike scope: text-producing keys (via `text` or `unshifted_codepoint`) use
 * the encoder's printable path. Returns `NullArgument` on NULL args.
 */
GhosttyRsResult ghostty_rs_surface_key(ghostty_rs_surface_t *surface, GhosttyRsInputKey event);

/**
 * Read the surface's visible screen as UTF-8 text (rows joined by `\n`,
 * trailing blanks on each row trimmed). Pre-M3 stand-in for `surface_draw`.
 *
 * Buffer convention (mirrors upstream `*_text` / vt-diff's formatter):
 * - Call with `buf == NULL` to get the required byte length in `*out_len`.
 * - Call again with a buffer of at least that size. On success `*out_len` is
 *   the number of bytes written (not counting a trailing NUL, which is written
 *   only if it fits).
 * - Returns [`GhosttyRsResult::OutOfSpace`] (and sets `*out_len` to the need)
 *   if `buf` is non-NULL but `buf_len` is too small.
 */
GhosttyRsResult ghostty_rs_surface_read_text(ghostty_rs_surface_t *surface,
                                             char *buf,
                                             size_t buf_len,
                                             size_t *out_len);

/**
 * Drain engine reply bytes (DSR/DA/CPR/DECRQSS answers the engine queued for
 * the PTY). Same buffer convention as [`ghostty_rs_surface_read_text`]. The
 * bytes are removed from the queue only when `buf` is non-NULL and large
 * enough (a size query with `buf == NULL` does not consume).
 */
GhosttyRsResult ghostty_rs_surface_take_pty_reply(ghostty_rs_surface_t *surface,
                                                  uint8_t *buf,
                                                  size_t buf_len,
                                                  size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GHOSTTY_RS_H */
