//! `cargo xtask gen-unicode` — generates `crates/ghostty-vt/src/unicode/tables.rs`.
//!
//! Port of ghostty's unicode table codegen (`src/unicode/props_uucode.zig` +
//! `src/build/uucode_config.zig` + the uucode property derivations). See
//! `docs/analysis/unicode.md` for the full derivation spec.
//!
//! Data source: UCD 17.0.0 files downloaded into `xtask/data/ucd/` (gitignored;
//! network at codegen time only — the generated tables.rs is checked in). Files are
//! parsed with `ucd-parse`, except three things it does not model, which are parsed
//! by hand: `# @missing: ...; W` directives in DerivedEastAsianWidth.txt, InCB
//! property *values* in DerivedCoreProperties.txt, and emoji-variation-sequences.txt.

use std::{fmt::Write as _, fs, path::Path, path::PathBuf, process::Command, str::FromStr};

use ucd_parse::{
    CoreProperty, EmojiProperty, GraphemeClusterBreak,
    extracted::{DerivedEastAsianWidth, DerivedGeneralCategory},
};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

pub const UNICODE_VERSION: &str = "17.0.0";
const UCD_BASE: &str = "https://www.unicode.org/Public/17.0.0/ucd";
const UCD_FILES: &[&str] = &[
    "extracted/DerivedGeneralCategory.txt",
    "extracted/DerivedEastAsianWidth.txt",
    "DerivedCoreProperties.txt",
    "auxiliary/GraphemeBreakProperty.txt",
    "emoji/emoji-data.txt",
    "emoji/emoji-variation-sequences.txt",
];

const NUM_CP: usize = 0x110000;
const BLOCK_SIZE: usize = 256;

pub fn run() -> Result<()> {
    let ucd_dir = PathBuf::from("xtask/data/ucd");
    download_ucd(&ucd_dir)?;

    let props = compute_properties(&ucd_dir)?;
    let (stage1, stage2, stage3) = build_lut(&props);
    eprintln!(
        "gen-unicode: stage1={} stage2={} stage3={} (block size {BLOCK_SIZE})",
        stage1.len(),
        stage2.len(),
        stage3.len(),
    );

    let out = render_tables(&stage1, &stage2, &stage3);
    let out_path = Path::new("crates/ghostty-vt/src/unicode/tables.rs");
    fs::write(out_path, out)?;
    eprintln!("gen-unicode: wrote {}", out_path.display());

    write_grapheme_control_fixture(&ucd_dir)?;
    Ok(())
}

/// Emits the UAX #29 `Grapheme_Cluster_Break ∈ {Control, CR, LF}` set as a test
/// fixture. The runtime table deliberately collapses these classes into `Other`
/// (the terminal filters controls before segmentation), so the oracle cross-check
/// tests need the original membership to classify intentional divergences.
fn write_grapheme_control_fixture(ucd_dir: &Path) -> Result<()> {
    let mut ranges: Vec<(u32, u32)> = Vec::new();
    for row in ucd_parse::parse::<_, GraphemeClusterBreak>(ucd_dir)? {
        if matches!(row.value.as_str(), "Control" | "CR" | "LF") {
            let mut cps = row.codepoints.into_iter();
            let first = cps.next().unwrap().value();
            let last = cps.last().map_or(first, |cp| cp.value());
            ranges.push((first, last));
        }
    }
    ranges.sort_unstable();

    let mut out = String::from(
        "# Codepoint ranges with Grapheme_Cluster_Break = Control, CR, or LF.\n\
         # DO NOT EDIT. Generated by `cargo xtask gen-unicode` from UCD ",
    );
    let _ = writeln!(out, "{UNICODE_VERSION}.");
    for (first, last) in ranges {
        let _ = writeln!(out, "{first:04X}..{last:04X}");
    }
    let out_path = Path::new("crates/ghostty-vt/tests/data/grapheme_control.txt");
    fs::write(out_path, out)?;
    eprintln!("gen-unicode: wrote {}", out_path.display());
    Ok(())
}

fn download_ucd(ucd_dir: &Path) -> Result<()> {
    for rel in UCD_FILES {
        let dest = ucd_dir.join(rel);
        if dest.exists() {
            continue;
        }
        fs::create_dir_all(dest.parent().unwrap())?;
        let url = format!("{UCD_BASE}/{rel}");
        eprintln!("gen-unicode: downloading {url}");
        let status = Command::new("curl")
            .args(["-fsSL", "-o"])
            .arg(&dest)
            .arg(&url)
            .status()?;
        if !status.success() {
            return Err(format!("download failed: {url}").into());
        }
    }
    Ok(())
}

/// General categories we branch on (everything else is `Other`).
#[derive(Clone, Copy, PartialEq, Eq)]
enum Gc {
    Control,
    Surrogate,
    LineSeparator,
    ParagraphSeparator,
    NonspacingMark,
    EnclosingMark,
    Other,
}

/// Raw UAX #29 Grapheme_Cluster_Break values (GraphemeBreakProperty.txt).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Gcb {
    Other,
    Prepend,
    Cr,
    Lf,
    Control,
    Extend,
    RegionalIndicator,
    SpacingMark,
    L,
    V,
    T,
    Lv,
    Lvt,
    Zwj,
}

/// Indic_Conjunct_Break (DerivedCoreProperties.txt `InCB` lines).
#[derive(Clone, Copy, PartialEq, Eq)]
enum Incb {
    None,
    Extend,
    Linker,
    Consonant,
}

/// The 17-value grapheme class stored in the table. Discriminants must match
/// `ghostty_vt::unicode::GraphemeBreakClass` (which mirrors uucode's
/// `GraphemeBreakNoControl`).
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
enum Gbnc {
    Other = 0,
    Prepend,
    RegionalIndicator,
    SpacingMark,
    L,
    V,
    T,
    Lv,
    Lvt,
    Zwj,
    Zwnj,
    ExtendedPictographic,
    EmojiModifierBase,
    EmojiModifier,
    IndicConjunctBreakExtend,
    IndicConjunctBreakLinker,
    IndicConjunctBreakConsonant,
}

impl Gbnc {
    const NAMES: [&'static str; 17] = [
        "Other",
        "Prepend",
        "RegionalIndicator",
        "SpacingMark",
        "L",
        "V",
        "T",
        "Lv",
        "Lvt",
        "Zwj",
        "Zwnj",
        "ExtendedPictographic",
        "EmojiModifierBase",
        "EmojiModifier",
        "IndicConjunctBreakExtend",
        "IndicConjunctBreakLinker",
        "IndicConjunctBreakConsonant",
    ];
}

/// Mirror of `ghostty_vt::unicode::Properties` (ghostty `src/unicode/props.zig`).
#[derive(Clone, Copy, PartialEq, Eq)]
struct Props {
    width: u8,
    width_zero_in_grapheme: bool,
    grapheme_break: Gbnc,
    emoji_vs_base: bool,
}

struct Ucd {
    gc: Vec<Gc>,
    eaw_wide: Vec<bool>, // East_Asian_Width in {W, F}, with @missing W defaults applied
    default_ignorable: Vec<bool>,
    gcb: Vec<Gcb>,
    incb: Vec<Incb>,
    emoji_modifier: Vec<bool>,
    emoji_modifier_base: Vec<bool>,
    extended_pictographic: Vec<bool>,
    emoji_vs_base: Vec<bool>,
}

fn parse_ucd(ucd_dir: &Path) -> Result<Ucd> {
    let mut ucd = Ucd {
        gc: vec![Gc::Other; NUM_CP],
        eaw_wide: vec![false; NUM_CP],
        default_ignorable: vec![false; NUM_CP],
        gcb: vec![Gcb::Other; NUM_CP],
        incb: vec![Incb::None; NUM_CP],
        emoji_modifier: vec![false; NUM_CP],
        emoji_modifier_base: vec![false; NUM_CP],
        extended_pictographic: vec![false; NUM_CP],
        emoji_vs_base: vec![false; NUM_CP],
    };

    // General category.
    for row in ucd_parse::parse::<_, DerivedGeneralCategory>(ucd_dir)? {
        let gc = match row.general_category.as_str() {
            "Cc" => Gc::Control,
            "Cs" => Gc::Surrogate,
            "Zl" => Gc::LineSeparator,
            "Zp" => Gc::ParagraphSeparator,
            "Mn" => Gc::NonspacingMark,
            "Me" => Gc::EnclosingMark,
            _ => continue,
        };
        for cp in row.codepoints.into_iter() {
            ucd.gc[cp.value() as usize] = gc;
        }
    }

    // East Asian Width. uucode (src/build/Ucd.zig parseEastAsianWidth) processes the
    // file line by line, honoring `# @missing: <range>; W` directives (unassigned
    // codepoints in CJK-default ranges are Wide). Mirror that exactly.
    let eaw_path = ucd_dir.join("extracted/DerivedEastAsianWidth.txt");
    for line in fs::read_to_string(&eaw_path)?.lines() {
        let trimmed = line.trim();
        if let Some(missing) = trimmed.strip_prefix("# @missing:") {
            let mut parts = missing.splitn(2, ';');
            let range = parse_range(parts.next().unwrap().trim())?;
            let value = parts
                .next()
                .ok_or("malformed @missing line")?
                .trim()
                .split(|c: char| c.is_whitespace() || c == '#')
                .next()
                .unwrap_or("");
            match value {
                "Neutral" => {}
                "Wide" => {
                    for cp in range.0..=range.1 {
                        ucd.eaw_wide[cp as usize] = true;
                    }
                }
                other => return Err(format!("unknown @missing EAW value: {other}").into()),
            }
            continue;
        }
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let row = DerivedEastAsianWidth::from_str(line)?;
        let wide = matches!(row.east_asian_width.as_str(), "W" | "F");
        for cp in row.codepoints.into_iter() {
            ucd.eaw_wide[cp.value() as usize] = wide;
        }
    }

    // DerivedCoreProperties: Default_Ignorable_Code_Point via ucd-parse (its parser
    // keeps only the property name, which is all we need there), InCB values by hand.
    for row in ucd_parse::parse::<_, CoreProperty>(ucd_dir)? {
        if row.property == "Default_Ignorable_Code_Point" {
            for cp in row.codepoints.into_iter() {
                ucd.default_ignorable[cp.value() as usize] = true;
            }
        }
    }
    let dcp_path = ucd_dir.join("DerivedCoreProperties.txt");
    for line in fs::read_to_string(&dcp_path)?.lines() {
        let data = line.split('#').next().unwrap_or("").trim();
        if data.is_empty() {
            continue;
        }
        let mut parts = data.split(';').map(str::trim);
        let (Some(range), Some(prop)) = (parts.next(), parts.next()) else {
            continue;
        };
        if prop != "InCB" {
            continue;
        }
        let value = match parts.next() {
            Some("Extend") => Incb::Extend,
            Some("Linker") => Incb::Linker,
            Some("Consonant") => Incb::Consonant,
            other => return Err(format!("unknown InCB value: {other:?}").into()),
        };
        let range = parse_range(range)?;
        for cp in range.0..=range.1 {
            ucd.incb[cp as usize] = value;
        }
    }

    // Grapheme_Cluster_Break.
    for row in ucd_parse::parse::<_, GraphemeClusterBreak>(ucd_dir)? {
        let gcb = match row.value.as_str() {
            "Prepend" => Gcb::Prepend,
            "CR" => Gcb::Cr,
            "LF" => Gcb::Lf,
            "Control" => Gcb::Control,
            "Extend" => Gcb::Extend,
            "Regional_Indicator" => Gcb::RegionalIndicator,
            "SpacingMark" => Gcb::SpacingMark,
            "L" => Gcb::L,
            "V" => Gcb::V,
            "T" => Gcb::T,
            "LV" => Gcb::Lv,
            "LVT" => Gcb::Lvt,
            "ZWJ" => Gcb::Zwj,
            other => return Err(format!("unknown GCB value: {other}").into()),
        };
        for cp in row.codepoints.into_iter() {
            ucd.gcb[cp.value() as usize] = gcb;
        }
    }

    // emoji-data.txt.
    for row in ucd_parse::parse::<_, EmojiProperty>(ucd_dir)? {
        let field = match row.property.as_str() {
            "Emoji_Modifier" => &mut ucd.emoji_modifier,
            "Emoji_Modifier_Base" => &mut ucd.emoji_modifier_base,
            "Extended_Pictographic" => &mut ucd.extended_pictographic,
            _ => continue,
        };
        for cp in row.codepoints.into_iter() {
            field[cp.value() as usize] = true;
        }
    }

    // emoji-variation-sequences.txt: a codepoint is an emoji VS base iff it heads
    // both a "text style" (VS15) and an "emoji style" (VS16) sequence. uucode
    // asserts is_text == is_emoji and stores the shared bit (build/tables.zig).
    let evs_path = ucd_dir.join("emoji/emoji-variation-sequences.txt");
    let mut vs_text = vec![false; NUM_CP];
    let mut vs_emoji = vec![false; NUM_CP];
    for line in fs::read_to_string(&evs_path)?.lines() {
        let data = line.split('#').next().unwrap_or("").trim();
        if data.is_empty() {
            continue;
        }
        let mut parts = data.split(';').map(str::trim);
        let (Some(seq), Some(style)) = (parts.next(), parts.next()) else {
            continue;
        };
        let mut cps = seq.split_whitespace();
        let base = u32::from_str_radix(cps.next().ok_or("empty sequence")?, 16)?;
        let selector = u32::from_str_radix(cps.next().ok_or("missing selector")?, 16)?;
        match (style, selector) {
            ("text style", 0xFE0E) => vs_text[base as usize] = true,
            ("emoji style", 0xFE0F) => vs_emoji[base as usize] = true,
            other => return Err(format!("unexpected variation sequence: {other:?}").into()),
        }
    }
    for cp in 0..NUM_CP {
        assert_eq!(vs_text[cp], vs_emoji[cp], "VS base mismatch at U+{cp:04X}");
        ucd.emoji_vs_base[cp] = vs_text[cp];
    }

    Ok(ucd)
}

fn parse_range(s: &str) -> Result<(u32, u32)> {
    match s.split_once("..") {
        Some((lo, hi)) => Ok((u32::from_str_radix(lo, 16)?, u32::from_str_radix(hi, 16)?)),
        None => {
            let cp = u32::from_str_radix(s, 16)?;
            Ok((cp, cp))
        }
    }
}

fn compute_properties(ucd_dir: &Path) -> Result<Vec<Props>> {
    let ucd = parse_ucd(ucd_dir)?;
    let mut props = Vec::with_capacity(NUM_CP);
    for cp in 0..NUM_CP as u32 {
        props.push(compute_one(&ucd, cp));
    }
    Ok(props)
}

/// Per-codepoint derivation. This fuses three layers of the Zig pipeline, in order:
/// uucode's grapheme_break derivation (uucode src/build/tables.zig:1008-1070) plus the
/// no-control collapse (uucode src/x/config_x/grapheme_break.zig), uucode's wcwidth
/// extension (uucode src/x/config_x/wcwidth.zig), and ghostty's width/property fusion
/// (ghostty src/build/uucode_config.zig `computeWidth`, src/unicode/props.zig).
fn compute_one(ucd: &Ucd, cp: u32) -> Props {
    let i = cp as usize;
    let gc = ucd.gc[i];
    let gcb = ucd.gcb[i];

    // --- grapheme break class (extended, then control/cr/lf collapsed to Other) ---
    let gbnc = if ucd.emoji_modifier[i] {
        assert_eq!(gcb, Gcb::Extend);
        Gbnc::EmojiModifier
    } else if ucd.emoji_modifier_base[i] {
        assert_eq!(gcb, Gcb::Other);
        assert!(ucd.extended_pictographic[i]);
        Gbnc::EmojiModifierBase
    } else if ucd.extended_pictographic[i] {
        assert_eq!(gcb, Gcb::Other);
        Gbnc::ExtendedPictographic
    } else {
        match ucd.incb[i] {
            Incb::Extend => {
                if cp == 0x200D {
                    assert_eq!(gcb, Gcb::Zwj);
                    Gbnc::Zwj
                } else {
                    assert_eq!(gcb, Gcb::Extend);
                    Gbnc::IndicConjunctBreakExtend
                }
            }
            Incb::Linker => {
                assert_eq!(gcb, Gcb::Extend);
                Gbnc::IndicConjunctBreakLinker
            }
            Incb::Consonant => {
                assert_eq!(gcb, Gcb::Other);
                Gbnc::IndicConjunctBreakConsonant
            }
            Incb::None => match gcb {
                // Every GCB=Extend cp is InCB Extend/Linker except U+200C ZWNJ.
                Gcb::Extend => {
                    assert_eq!(cp, 0x200C, "unexpected InCB=None Extend at U+{cp:04X}");
                    Gbnc::Zwnj
                }
                // ZWJ always has InCB=Extend; it cannot reach here.
                Gcb::Zwj => unreachable!("ZWJ must be InCB=Extend"),
                // The no-control collapse (grapheme_break_no_control).
                Gcb::Cr | Gcb::Lf | Gcb::Control => Gbnc::Other,
                Gcb::Other => Gbnc::Other,
                Gcb::Prepend => Gbnc::Prepend,
                Gcb::RegionalIndicator => Gbnc::RegionalIndicator,
                Gcb::SpacingMark => Gbnc::SpacingMark,
                Gcb::L => Gbnc::L,
                Gcb::V => Gbnc::V,
                Gcb::T => Gbnc::T,
                Gcb::Lv => Gbnc::Lv,
                Gcb::Lvt => Gbnc::Lvt,
            },
        }
    };

    // --- wcwidth_standalone / wcwidth_zero_in_grapheme (uucode wcwidth extension) ---
    let width: u8 = if matches!(
        gc,
        Gc::Control | Gc::Surrogate | Gc::LineSeparator | Gc::ParagraphSeparator
    ) {
        0
    } else if cp == 0x00AD {
        1 // soft hyphen: terminal compat exception
    } else if ucd.default_ignorable[i] {
        0
    } else if cp == 0x2E3A {
        2 // two-em dash
    } else if cp == 0x2E3B {
        3 // three-em dash (ghostty clamps to 2 below)
    } else if ucd.eaw_wide[i] || gcb == Gcb::RegionalIndicator {
        // East Asian Wide/Fullwidth, or a lone regional indicator (UTS #51 C3:
        // renders as a letter-in-a-box).
        2
    } else {
        1
    };
    let wcwidth_standalone = if cp == 0x20E3 { 2 } else { width }; // combining enclosing keycap
    let wcwidth_zero_in_grapheme = width == 0
        || ucd.emoji_modifier[i]
        || matches!(gc, Gc::NonspacingMark | Gc::EnclosingMark)
        || matches!(gcb, Gcb::V | Gcb::T | Gcb::Prepend);

    // --- ghostty width fusion (src/build/uucode_config.zig computeWidth) ---
    let ghostty_width =
        if wcwidth_zero_in_grapheme && !ucd.emoji_modifier[i] && gbnc != Gbnc::Prepend {
            0
        } else {
            wcwidth_standalone.min(2)
        };

    Props {
        width: ghostty_width,
        width_zero_in_grapheme: wcwidth_zero_in_grapheme,
        grapheme_break: gbnc,
        emoji_vs_base: ucd.emoji_vs_base[i],
    }
}

/// Build the 3-stage LUT (port of ghostty src/unicode/lut.zig `Generator.generate`,
/// block size 256). stage1 maps `cp >> 8` to the offset of that block's run in
/// stage2; stage2 entries index the deduplicated stage3 values.
fn build_lut(props: &[Props]) -> (Vec<u16>, Vec<u16>, Vec<Props>) {
    use std::collections::HashMap;

    let mut stage1: Vec<u16> = Vec::with_capacity(NUM_CP / BLOCK_SIZE);
    let mut stage2: Vec<u16> = Vec::new();
    let mut stage3: Vec<Props> = Vec::new();
    let mut block_map: HashMap<Vec<u16>, u16> = HashMap::new();

    for chunk in props.chunks(BLOCK_SIZE) {
        let block: Vec<u16> = chunk
            .iter()
            .map(|p| {
                let idx = stage3.iter().position(|q| q == p).unwrap_or_else(|| {
                    stage3.push(*p);
                    stage3.len() - 1
                });
                u16::try_from(idx).expect("stage3 index overflows u16")
            })
            .collect();

        let offset = *block_map.entry(block.clone()).or_insert_with(|| {
            let offset = u16::try_from(stage2.len()).expect("stage2 offset overflows u16");
            stage2.extend_from_slice(&block);
            offset
        });
        stage1.push(offset);
    }

    assert!(stage1.len() <= u16::MAX as usize);
    (stage1, stage2, stage3)
}

fn render_tables(stage1: &[u16], stage2: &[u16], stage3: &[Props]) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        "\
//! Unicode property lookup tables (3-stage LUT, ghostty `src/unicode/lut.zig` layout).
//!
//! DO NOT EDIT. Generated by `cargo xtask gen-unicode` (xtask/src/gen_unicode.rs)
//! from the Unicode Character Database version {UNICODE_VERSION}.
//!
//! Lookup: `STAGE3[STAGE2[(STAGE1[cp >> 8] + (cp & 0xFF)) as usize] as usize]`.
//! stage1: {s1} entries (one per 256-codepoint block, 0..=0x10FFFF);
//! stage2: {s2} entries ({blocks} deduplicated blocks); stage3: {s3} unique property sets.

use super::props::{{GraphemeBreakClass as G, Properties}};

/// Unicode Character Database version these tables were generated from.
pub const UNICODE_VERSION: &str = \"{UNICODE_VERSION}\";

",
        s1 = stage1.len(),
        s2 = stage2.len(),
        s3 = stage3.len(),
        blocks = stage2.len() / BLOCK_SIZE,
    );

    render_u16_array(&mut out, "STAGE1", stage1);
    render_u16_array(&mut out, "STAGE2", stage2);

    let _ = writeln!(out, "#[rustfmt::skip]");
    let _ = writeln!(out, "pub static STAGE3: [Properties; {}] = [", stage3.len());
    for p in stage3 {
        let _ = writeln!(
            out,
            "    Properties::new({}, {}, G::{}, {}),",
            p.width,
            p.width_zero_in_grapheme,
            Gbnc::NAMES[p.grapheme_break as usize],
            p.emoji_vs_base,
        );
    }
    let _ = writeln!(out, "];");
    out
}

fn render_u16_array(out: &mut String, name: &str, data: &[u16]) {
    let _ = writeln!(out, "#[rustfmt::skip]");
    let _ = writeln!(out, "pub static {name}: [u16; {}] = [", data.len());
    for chunk in data.chunks(16) {
        let line: Vec<String> = chunk.iter().map(u16::to_string).collect();
        let _ = writeln!(out, "    {},", line.join(", "));
    }
    let _ = writeln!(out, "];");
    let _ = writeln!(out);
}
