//! Unicode handling for the terminal (port of ghostty `src/unicode/`).
//!
//! Two questions on the hot path, answered from precomputed multi-stage lookup
//! tables: how many terminal cells does a codepoint or grapheme cluster occupy
//! (0, 1, or 2), and is there a grapheme cluster break between two adjacent
//! codepoints (streaming UAX #29 with terminal tailorings, for mode 2027)?
//!
//! Tables are generated by `cargo xtask gen-unicode` (UCD data → 3-stage LUT);
//! see `docs/analysis/unicode.md` for how the properties are derived.

mod grapheme;
mod props;
mod tables;

pub use grapheme::{
    BreakState, GraphemeWidth, GraphemeWidthEffect, grapheme_break, grapheme_width,
    grapheme_width_effect,
};
pub use props::{GraphemeBreakClass, Properties};
pub use tables::UNICODE_VERSION;

/// Returns the precomputed [`Properties`] for a codepoint.
///
/// Values above U+10FFFF (possible for FFI-facing u32 input) return ghostty's
/// out-of-range fallback: width 1, zero-width-in-grapheme, no break class
/// (ghostty `src/unicode/props_uucode.zig` `get`).
#[inline]
pub fn properties(cp: u32) -> Properties {
    if cp > 0x10FFFF {
        return Properties::new(1, true, GraphemeBreakClass::Other, false);
    }
    let block = tables::STAGE1[(cp >> 8) as usize] as usize;
    let index = tables::STAGE2[block + (cp & 0xFF) as usize] as usize;
    tables::STAGE3[index]
}

/// Returns the terminal display width of a codepoint in grid cells: 0, 1, or 2.
///
/// This is the same width table the terminal uses when laying out printed text:
/// 0 for zero-width codepoints (controls, combining marks, default-ignorables,
/// surrogates), 2 for wide codepoints (East Asian Wide/Fullwidth, regional
/// indicators, clamped at 2), and 1 otherwise.
///
/// This operates on a single codepoint and cannot account for
/// grapheme-cluster-level width rules (VS16, combining sequences); callers
/// needing cluster-accurate widths should use [`grapheme_width`]. Summing
/// per-codepoint widths is only correct when mode 2027 is disabled.
#[inline]
pub fn codepoint_width(cp: u32) -> u8 {
    properties(cp).width
}

#[cfg(test)]
mod tests {
    //! Port of the inline tests in ghostty `src/unicode/main.zig`.

    use super::*;

    #[test]
    fn codepoint_width_table() {
        // Narrow (width 1)
        assert_eq!(1, codepoint_width('a' as u32));
        assert_eq!(1, codepoint_width(' ' as u32));
        assert_eq!(1, codepoint_width(0x10FFFF)); // max codepoint

        // C0/C1 control characters (width 0)
        assert_eq!(0, codepoint_width(0x00)); // NUL
        assert_eq!(0, codepoint_width(0x07)); // BEL
        assert_eq!(0, codepoint_width(0x1B)); // ESC
        assert_eq!(0, codepoint_width(0x7F)); // DEL
        assert_eq!(0, codepoint_width(0x80)); // C1 PAD

        // Zero-width codepoints
        assert_eq!(0, codepoint_width(0x0301)); // combining acute
        assert_eq!(0, codepoint_width(0x200B)); // zero width space
        assert_eq!(0, codepoint_width(0x200D)); // ZWJ
        assert_eq!(0, codepoint_width(0xFE0F)); // VS16
        assert_eq!(0, codepoint_width(0xD800)); // surrogate

        // Wide (width 2)
        assert_eq!(2, codepoint_width(0x4E00)); // CJK ideograph
        assert_eq!(2, codepoint_width(0xFF21)); // fullwidth A
        assert_eq!(2, codepoint_width(0xAC00)); // Hangul syllable
        assert_eq!(2, codepoint_width(0x1F600)); // emoji
        assert_eq!(2, codepoint_width(0x1F1E6)); // regional indicator
        assert_eq!(2, codepoint_width(0x2E3B)); // three-em dash (clamped)
    }

    #[test]
    fn codepoint_width_out_of_range() {
        // Port of `src/terminal/c/unicode.zig` "codepoint_width out of range".
        assert_eq!(1, codepoint_width(0x110000));
        assert_eq!(1, codepoint_width(u32::MAX));
    }
}
